import type { Briefing } from '@/lib/assistant/briefings'
import { requestJson } from '@/lib/integrations/sync/http'

/**
 * Writing a briefing into a Notion database.
 *
 * The one write this product makes to Notion, and it is additive: a new page
 * per briefing, in a database the workspace chose, and nothing else touched.
 * There is no "update the page we made yesterday" because a briefing is a
 * statement about a moment, and yesterday's should keep saying what it said.
 *
 * What is kept honest on the way in:
 *
 * **Figures go in as properties as well as prose.** A Notion database with a
 * `Net revenue` column can be sorted, filtered and charted; a page that only
 * mentions the number in a paragraph cannot. Properties are created only if
 * the database has them — Notion rejects unknown properties — so the builder
 * takes the database's schema and fills what it can, and the rest goes into
 * the body where nothing is lost.
 *
 * **Rich text is chunked at 2,000 characters.** That is Notion's limit per
 * rich-text item. A long attention line that exceeded it would fail the whole
 * page create, silently, on the one day the briefing had the most to say.
 *
 * **Demo data is a callout at the top**, not a footnote. The page will be read
 * in Notion by someone who never saw the app's own banner.
 *
 * The token is opened by the caller and passed in; it is never logged, and
 * `requestJson` discards Notion's error bodies, which echo it.
 */

const API = 'https://api.notion.com/v1'
const VERSION = '2022-06-28'
/** Notion's limit per rich-text item. */
export const RICH_TEXT_LIMIT = 2_000
/** Notion's limit per page-create request. */
const BLOCK_LIMIT = 100

type RichText = { type: 'text'; text: { content: string; link?: { url: string } | null } }
type Block = Record<string, unknown>

/** Splits text into rich-text items Notion will accept, on word boundaries. */
export function richText(text: string): RichText[] {
  const items: RichText[] = []
  let rest = text
  while (rest.length > RICH_TEXT_LIMIT) {
    let cut = rest.lastIndexOf(' ', RICH_TEXT_LIMIT)
    if (cut < RICH_TEXT_LIMIT / 2) cut = RICH_TEXT_LIMIT
    items.push({ type: 'text', text: { content: rest.slice(0, cut) } })
    rest = rest.slice(cut).replace(/^\s+/, '')
  }
  if (rest || items.length === 0) items.push({ type: 'text', text: { content: rest } })
  return items
}

const paragraph = (text: string): Block => ({ object: 'block', type: 'paragraph', paragraph: { rich_text: richText(text) } })
const heading = (text: string): Block => ({ object: 'block', type: 'heading_2', heading_2: { rich_text: richText(text) } })
const bullet = (text: string): Block => ({ object: 'block', type: 'bulleted_list_item', bulleted_list_item: { rich_text: richText(text) } })
const todo = (text: string): Block => ({ object: 'block', type: 'to_do', to_do: { rich_text: richText(text), checked: false } })
const callout = (text: string, emoji: string): Block => ({
  object: 'block',
  type: 'callout',
  callout: { rich_text: richText(text), icon: { type: 'emoji', emoji } },
})

export function briefingBlocks(briefing: Briefing): Block[] {
  const blocks: Block[] = []

  if (briefing.isDemo) {
    blocks.push(callout('Demonstration data. These figures are synthetic.', '⚠️'))
  }
  blocks.push(callout(briefing.headline, '📌'))

  blocks.push(heading('Figures'))
  for (const line of briefing.lines) {
    blocks.push(bullet(`${line.label}: ${line.value}${line.change ? ` (${line.change})` : ''}`))
  }

  if (briefing.attention.length > 0) {
    blocks.push(heading('Needs a decision'))
    for (const item of briefing.attention) blocks.push(todo(item))
  }

  if (briefing.caveats.length > 0) {
    blocks.push(heading('Caveats'))
    for (const item of briefing.caveats) blocks.push(bullet(item))
  }

  if (briefing.followUps.length > 0) {
    blocks.push(heading('Ask next'))
    for (const item of briefing.followUps) blocks.push(bullet(item))
  }

  blocks.push(
    paragraph(
      `Period: ${briefing.period}${briefing.comparisonPeriod ? ` (compared with ${briefing.comparisonPeriod})` : ''}. Generated by Aurelis.`,
    ),
  )

  return blocks.slice(0, BLOCK_LIMIT)
}

/** The database's property schema, as Notion reports it. */
export type DatabaseSchema = Record<string, { type: string }>

/**
 * Properties for the new page, matched to what the database actually has.
 *
 * The title property is whichever one is typed `title` — its name varies.
 * Other properties are filled only when a column of the right type exists
 * under the figure's label, so an unconfigured database gets a page with a
 * title and a body and no rejected request.
 */
export function briefingProperties(
  briefing: Briefing,
  schema: DatabaseSchema,
  at: Date,
): Record<string, unknown> {
  const properties: Record<string, unknown> = {}

  const titleName = Object.entries(schema).find(([, p]) => p.type === 'title')?.[0] ?? 'Name'
  properties[titleName] = { title: richText(`${briefing.title} — ${briefing.period}`) }

  const set = (name: string, value: unknown) => {
    if (name in schema) properties[name] = value
  }

  set('Date', { date: { start: at.toISOString().slice(0, 10) } })
  set('Kind', { select: { name: briefing.kind } })
  set('Period', { rich_text: richText(briefing.period) })
  set('Demo data', { checkbox: briefing.isDemo })

  for (const line of briefing.lines) {
    const column = schema[line.label]
    if (!column) continue
    if (column.type === 'rich_text') properties[line.label] = { rich_text: richText(line.value) }
    else if (column.type === 'number') {
      const numeric = Number(line.value.replace(/[^0-9.-]/g, ''))
      if (Number.isFinite(numeric)) properties[line.label] = { number: numeric }
    }
  }

  return properties
}

export type NotionWriteResult =
  | { ok: true; pageId: string; url: string | null }
  | { ok: false; detail: string; retryable: boolean }

/**
 * Creates the page. Reads the database schema first, so properties match.
 * Never throws: a failed write is an outcome the sweep records, not an
 * exception that stops the other workspaces' briefings.
 */
export async function createBriefingPage(input: {
  token: string
  databaseId: string
  briefing: Briefing
  at: Date
  fetch?: typeof globalThis.fetch
  sleep?: (ms: number) => Promise<void>
}): Promise<NotionWriteResult> {
  const doFetch = input.fetch ?? globalThis.fetch
  const sleep = input.sleep ?? ((ms: number) => new Promise((r) => setTimeout(r, ms)))
  const headers = {
    authorization: `Bearer ${input.token}`,
    'notion-version': VERSION,
    'content-type': 'application/json',
  }

  if (!/^[0-9a-f-]{32,36}$/i.test(input.databaseId)) {
    return { ok: false, retryable: false, detail: 'The Notion database id on this connection is not valid.' }
  }

  try {
    const { body: database } = await requestJson<{ properties?: DatabaseSchema }>(
      `${API}/databases/${input.databaseId}`,
      { headers },
      { fetch: doFetch, sleep },
    )

    const { body: page } = await requestJson<{ id: string; url?: string }>(
      `${API}/pages`,
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          parent: { database_id: input.databaseId },
          properties: briefingProperties(input.briefing, database.properties ?? {}, input.at),
          children: briefingBlocks(input.briefing),
        }),
      },
      { fetch: doFetch, sleep },
    )

    return { ok: true, pageId: page.id, url: page.url ?? null }
  } catch (error) {
    const retryable = (error as { retryable?: boolean }).retryable ?? false
    return {
      ok: false,
      retryable,
      detail: error instanceof Error ? error.message : 'The page could not be created.',
    }
  }
}
