/** GLOSSARY — the words an auction throws at a beginner, each in one or two plain sentences. */

export type Term = { term: string; meaning: string; tags: string[] }

export const GLOSSARY: Term[] = [
  { term: 'Hammer price', meaning: 'The winning bid, before any fee. Every fee is added to it.', tags: ['bidding', 'fees'] },
  { term: 'Buyer fee (buyer\'s premium)', meaning: 'What the auction charges the winner on top of the hammer price. A percentage, a sliding scale, or a flat amount.', tags: ['fees'] },
  { term: 'Reserve', meaning: 'The seller\'s secret minimum. If bidding ends below it, the car does not sell. "No reserve" means the high bid wins whatever it is.', tags: ['bidding'] },
  { term: 'Proxy bid (max bid)', meaning: 'You enter your maximum once and the site bids for you in small steps up to it. The safest way to bid.', tags: ['bidding'] },
  { term: 'Sniping', meaning: 'Bidding in the last seconds so nobody can answer. It works on sites with a hard end time (eBay) and not on sites that extend the clock (Cars & Bids, Bring a Trailer).', tags: ['bidding'] },
  { term: 'Bid extension (soft close)', meaning: 'A rule that adds time when a bid lands in the final minutes, so the auction ends only when bidding stops.', tags: ['bidding'] },
  { term: 'Increment', meaning: 'The smallest step a bid can rise by. Set by the site or the auctioneer, usually by price band.', tags: ['bidding'] },
  { term: 'Pre-bid', meaning: 'A maximum you enter before a live lane starts. The system bids for you when the lot comes up.', tags: ['bidding', 'salvage'] },
  { term: 'Live lane (virtual auction)', meaning: 'Lots sold one after another by an auctioneer, in person or streamed. Each lot closes in under a minute.', tags: ['bidding'] },
  { term: 'As is, where is', meaning: 'No warranty, no returns, and you collect it where it sits.', tags: ['policy'] },
  { term: 'Buyers Guide', meaning: 'The window sticker the FTC requires on every used car a dealer sells, saying whether it has a warranty or is as-is.', tags: ['law'] },
  { term: 'Clean title', meaning: 'A title with no brand. What a beginner buys.', tags: ['title'] },
  { term: 'Salvage title', meaning: 'An insurer declared the car a total loss. It cannot be registered until rebuilt and inspected. Worth far less, always.', tags: ['title'] },
  { term: 'Rebuilt (reconstructed) title', meaning: 'A salvage car that passed a state inspection. Legal to drive; hard to insure fully and to resell.', tags: ['title'] },
  { term: 'Flood title', meaning: 'Water damage. Electrical trouble for life. Avoid.', tags: ['title'] },
  { term: 'Lemon (buy-back) title', meaning: 'The maker bought the car back under a lemon law for defects it could not fix.', tags: ['title'] },
  { term: 'Junk / non-repairable / certificate of destruction', meaning: 'Cannot be registered, ever. Parts only.', tags: ['title'] },
  { term: 'Bill of sale only', meaning: 'Sold without a title. Registering it is hard or impossible. Skip it.', tags: ['title'] },
  { term: 'Title washing', meaning: 'Moving a branded car through a state that drops the brand. NMVTIS still shows the total loss.', tags: ['title', 'law'] },
  { term: 'NMVTIS', meaning: 'The federal title database that records brands, odometer readings at title events and total-loss reports. Reports cost a small fee.', tags: ['law', 'title'] },
  { term: 'History report', meaning: 'A paid report (Carfax, AutoCheck, an NMVTIS provider) of title brands, accidents, owners and odometer readings.', tags: ['title'] },
  { term: 'VIN', meaning: 'The 17-character vehicle identification number. On the dash, the door sticker and the title. No I, O or Q.', tags: ['basics'] },
  { term: 'Odometer statement', meaning: 'The written mileage disclosure federal law requires on every transfer for the first 20 model years (2011 and newer).', tags: ['law'] },
  { term: 'Runs and drives', meaning: 'The car started and moved under its own power at the yard. Not a promise that it is road-worthy.', tags: ['condition'] },
  { term: 'Condition report (CR)', meaning: 'A dealer auction\'s inspection write-up with a grade from 0 to 5 and a damage list. A 3.5 is an average trade-in.', tags: ['condition'] },
  { term: 'Sale lights (green, yellow, red)', meaning: 'A dealer auction\'s promise level. Green: full arbitration. Yellow: announced problems excluded. Red: as-is except odometer, title and frame.', tags: ['policy'] },
  { term: 'Arbitration', meaning: 'A dealer auction\'s process for disputing an undisclosed problem, inside a short window from the sale day.', tags: ['policy'] },
  { term: 'Gate fee', meaning: 'A salvage yard\'s charge to release a car to you or your carrier.', tags: ['fees', 'salvage'] },
  { term: 'Internet bid fee', meaning: 'A salvage auction\'s extra charge when you win online.', tags: ['fees', 'salvage'] },
  { term: 'Storage fee', meaning: 'A daily charge once the free days after payment run out.', tags: ['fees'] },
  { term: 'Broker', meaning: 'A registered buyer who bids at salvage auctions for people who cannot register themselves, for a fee.', tags: ['salvage'] },
  { term: 'Dealer licence', meaning: 'A state licence that opens dealer-only auctions and lets you sell above your state\'s yearly limit.', tags: ['law'] },
  { term: 'Surety bond', meaning: 'An insurance-like guarantee the state requires from dealers. You pay a yearly premium.', tags: ['law'] },
  { term: 'Floor plan', meaning: 'A dealer\'s credit line for buying inventory.', tags: ['dealer'] },
  { term: 'Title jumping', meaning: 'Selling a car without titling it in your name first. Illegal everywhere.', tags: ['law'] },
  { term: 'Curbstoning', meaning: 'Selling cars as a fake private seller to dodge dealer rules. Illegal.', tags: ['law'] },
  { term: 'Comps (comparables)', meaning: 'Other listings of the same car, similar year and miles. Gavel\'s estimate is their median, adjusted for mileage.', tags: ['gavel'] },
  { term: 'Steal score', meaning: 'Gavel\'s 0 to 100 read of how far a car sits under its comparables, after condition, title and demand adjustments.', tags: ['gavel'] },
  { term: 'PAPER bid', meaning: 'A bid Gavel records for practice. Nothing is sent to any auction.', tags: ['gavel'] },
  { term: 'Sniper (in Gavel)', meaning: 'A saved search with a budget: makes, models, years, and the most you will spend. It scans, ranks and, on paper, fires your bid plan.', tags: ['gavel'] },
  { term: 'PDR', meaning: 'Paintless dent repair. A mobile technician removes dings without paint.', tags: ['fixes'] },
  { term: 'OBD-II', meaning: 'The port under the dash. A cheap scanner reads fault codes and whether they were recently cleared.', tags: ['fixes'] },
  { term: 'Pre-purchase inspection (PPI)', meaning: 'A paid inspection by an independent mechanic before you buy. Worth it on any car over a few thousand dollars.', tags: ['condition'] },
  { term: 'Open carrier / enclosed carrier', meaning: 'The two kinds of car transport. Open is the normal choice; enclosed for valuable cars.', tags: ['basics'] },
  { term: 'Resale certificate', meaning: 'A state document that lets a dealer buy without paying sales tax at the auction.', tags: ['law', 'dealer'] },
]
