import Link from 'next/link'; import {allBooks,allProducts} from '@/lib/content'; import {ProductCard,BookCard} from '@/components/cards'; import {HomeHero,EmailCapture} from '@/components/HomeHero';
export default function Home(){const featured=allProducts.filter(p=>p.featured).slice(0,3);return <>
  <HomeHero/>
  <section className="light-section edit-section"><div className="section-intro" data-reveal><p className="eyebrow">The edit — shop now</p><h2>Objects of<br/><em>quiet utility.</em></h2><Link href="/shop">VIEW THE COMPLETE EDIT →</Link></div><div className="featured-grid">{featured.map((p,i)=><ProductCard product={p} index={i} key={p.slug} className={i===0?'featured-main':''}/>)}</div></section>
  <section className="magazine-strip"><div className="magazine-heading"><p className="eyebrow">Current issue / 2026</p><h2>THREE<br/>RITUALS</h2></div><div className="magazine-items">{[['01','THE SIGNATURE','An atmosphere, hand-poured.','/shop/ic-signature-candle'],['02','THE CARRY','Everyday utility, recast.','/shop/ic-linen-tote'],['03','THE RESET','Tools that earn their space.','/shop/cleaning-picks']].map(x=><Link href={x[3]} key={x[0]}><b>{x[0]}</b><p className="eyebrow">{x[1]}</p><h3>{x[2]}</h3><span>EXPLORE ↗</span></Link>)}</div></section>
  <section className="library-home"><div className="library-title" data-reveal><p className="eyebrow">Interior intelligence</p><h2>THE<br/><em>LIBRARY</em></h2><p>Field guides for spaces that support the life within them.</p></div><div className="book-row">{allBooks.map(b=><BookCard book={b} key={b.slug}/>)}</div></section>
  <section className="candle-feature"><div className="candle-copy" data-reveal><p className="eyebrow">Hand-poured. Considered.</p><h2>A light for<br/>the <em>in-between.</em></h2><p>The signature candle: designed as an object, experienced as an atmosphere.</p><Link href="/shop/ic-signature-candle">SHOP CANDLES →</Link></div><div className="candle-image"><span>◇</span><img src="/images/candle-hero.svg" alt="InteriorCleanse signature candle"/><i>01 / SIGNATURE OBJECT</i></div></section>
  <section className="manifesto" data-reveal><p>"We believe a well-kept home is the foundation of a <em>well-kept life.</em>"</p><span>— THE INTERIORCLEANSE PHILOSOPHY</span></section>
  <section className="email-section"><p className="eyebrow">Private correspondence</p><h2>The next edit,<br/>quietly delivered.</h2><EmailCapture/></section>
  </>}
