'use client'

import { useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { Button, Eyebrow, Field, Panel, inputClass } from '@/components/ui'
import { describeFactors, normaliseCode, type FactorSummary } from '@/lib/security/mfa'
import { supabaseBrowser } from '@/lib/supabase/client'

/**
 * Enrolling, listing and removing a second factor.
 *
 * TOTP through Supabase Auth: the secret is generated by the auth server and
 * shown once as a QR code and a text key; this product never sees a code
 * except to pass it on for verification, and never stores one. Removing the
 * last factor is allowed — it is the person's account — but says what it
 * means, and platform staff are told the console will close behind them.
 */
export function MfaPanel({ isPlatformStaff }: { isPlatformStaff: boolean }) {
  const router = useRouter()
  const [factors, setFactors] = useState<FactorSummary[] | null>(null)
  const [enrolling, setEnrolling] = useState<{ id: string; qr: string; secret: string } | null>(null)
  const [name, setName] = useState('Authenticator app')
  const [code, setCode] = useState('')
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState<{ tone: 'ok' | 'bad'; text: string } | null>(null)

  async function refresh() {
    const { data } = await supabaseBrowser().auth.mfa.listFactors()
    setFactors(describeFactors(data?.all ?? []))
  }

  useEffect(() => {
    const frame = requestAnimationFrame(() => void refresh())
    return () => cancelAnimationFrame(frame)
  }, [])

  async function beginEnrol() {
    setBusy(true)
    setMessage(null)
    const { data, error } = await supabaseBrowser().auth.mfa.enroll({
      factorType: 'totp',
      friendlyName: name.trim() || 'Authenticator app',
    })
    setBusy(false)
    if (error || !data) {
      setMessage({ tone: 'bad', text: 'Enrolment could not be started. Try again in a moment.' })
      return
    }
    setEnrolling({ id: data.id, qr: data.totp.qr_code, secret: data.totp.secret })
  }

  async function confirmEnrol(event: React.FormEvent) {
    event.preventDefault()
    if (!enrolling) return
    const digits = normaliseCode(code)
    if (!digits) {
      setMessage({ tone: 'bad', text: 'Enter the six-digit code the app shows.' })
      return
    }
    setBusy(true)
    const supabase = supabaseBrowser()
    const challenge = await supabase.auth.mfa.challenge({ factorId: enrolling.id })
    const verify = challenge.data
      ? await supabase.auth.mfa.verify({ factorId: enrolling.id, challengeId: challenge.data.id, code: digits })
      : { error: challenge.error }
    setBusy(false)
    if (verify.error) {
      setMessage({ tone: 'bad', text: 'That code did not match. Scan again if you set the app up twice.' })
      setCode('')
      return
    }
    setEnrolling(null)
    setCode('')
    setMessage({
      tone: 'ok',
      text: 'Second factor on. From now on a password alone does not sign you in, anywhere.',
    })
    await refresh()
    // The server reads the new assurance level on the next request.
    router.refresh()
  }

  async function cancelEnrol() {
    if (enrolling) await supabaseBrowser().auth.mfa.unenroll({ factorId: enrolling.id })
    setEnrolling(null)
    setCode('')
    await refresh()
  }

  async function remove(factor: FactorSummary) {
    const last = factors?.filter((f) => f.status === 'verified').length === 1 && factor.status === 'verified'
    const warning = last
      ? isPlatformStaff
        ? 'This is your only second factor. Removing it closes the owner console to you until you enrol another. Remove it?'
        : 'This is your only second factor. Removing it means a password alone signs you in again. Remove it?'
      : `Remove “${factor.friendlyName}”?`
    if (!window.confirm(warning)) return
    setBusy(true)
    const { error } = await supabaseBrowser().auth.mfa.unenroll({ factorId: factor.id })
    setBusy(false)
    setMessage(
      error
        ? { tone: 'bad', text: 'That factor could not be removed. Sign in again and retry.' }
        : { tone: 'ok', text: 'Removed.' },
    )
    await refresh()
    router.refresh()
  }

  async function signOutEverywhere() {
    if (!window.confirm('Sign out of every device and browser, including this one?')) return
    await supabaseBrowser().auth.signOut({ scope: 'global' })
    router.replace('/login')
  }

  const verified = factors?.filter((f) => f.status === 'verified') ?? []

  return (
    <Panel className={verified.length === 0 ? 'border-amber/40' : undefined}>
      <Eyebrow>Second factor</Eyebrow>
      <h2 className="text-lg font-semibold text-ink">
        {factors === null
          ? 'Checking…'
          : verified.length === 0
            ? 'Not set up'
            : `On · ${verified.length} ${verified.length === 1 ? 'authenticator' : 'authenticators'}`}
      </h2>
      <p className="mt-2 text-sm text-muted">
        An authenticator app (1Password, Google Authenticator, Authy, or any TOTP app) adds a
        code that changes every thirty seconds. With one enrolled, the server stops accepting a
        password-only session everywhere — web, extension and desktop app — and the owner console
        requires it.
      </p>

      {message ? (
        <p role="status" className={`mt-3 text-sm ${message.tone === 'ok' ? 'text-positive' : 'text-negative'}`}>
          {message.text}
        </p>
      ) : null}

      {verified.length > 0 ? (
        <ul className="mt-4 space-y-2">
          {verified.map((factor) => (
            <li key={factor.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-hairline bg-panelRaised px-3 py-2 text-sm">
              <span className="text-ink">{factor.friendlyName}</span>
              <span className="flex items-center gap-3">
                <span className="text-xs text-muted">since {new Date(factor.createdAt).toLocaleDateString()}</span>
                <button type="button" onClick={() => remove(factor)} disabled={busy} className="text-xs text-muted hover:text-negative">
                  Remove
                </button>
              </span>
            </li>
          ))}
        </ul>
      ) : null}

      {enrolling ? (
        <form onSubmit={confirmEnrol} className="mt-5 grid gap-5 rounded-lg border border-hairline bg-ground p-4 sm:grid-cols-[auto_1fr]">
          {/* The QR is an SVG data URI from the auth server; shown once. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={enrolling.qr} alt="QR code to scan with an authenticator app" width={168} height={168} className="rounded-lg bg-white p-2" />
          <div className="space-y-3">
            <p className="text-sm text-ink">Scan this with your authenticator app, then enter the code it shows.</p>
            <p className="text-xs text-muted">
              Cannot scan? Enter this key by hand:{' '}
              <code className="select-all break-all text-ink">{enrolling.secret}</code>
            </p>
            <Field label="Six-digit code">
              <input
                className={`${inputClass} tabular tracking-[0.4em]`}
                inputMode="numeric"
                autoComplete="one-time-code"
                maxLength={7}
                value={code}
                onChange={(event) => setCode(event.target.value)}
                required
              />
            </Field>
            <div className="flex gap-2">
              <Button type="submit" disabled={busy}>
                {busy ? 'Checking…' : 'Turn on'}
              </Button>
              <Button type="button" variant="ghost" onClick={cancelEnrol} disabled={busy}>
                Cancel
              </Button>
            </div>
          </div>
        </form>
      ) : (
        <div className="mt-5 flex flex-wrap items-end gap-3">
          <Field label="Name this device" hint="So you know which to remove later.">
            <input className={inputClass} value={name} onChange={(event) => setName(event.target.value)} maxLength={40} />
          </Field>
          <Button onClick={beginEnrol} disabled={busy || factors === null}>
            {verified.length > 0 ? 'Add another' : 'Set up'}
          </Button>
        </div>
      )}

      <div className="mt-6 border-t border-hairline pt-4">
        <Button variant="ghost" onClick={signOutEverywhere} disabled={busy}>
          Sign out everywhere
        </Button>
        <p className="mt-1 text-xs text-muted">Ends every session on every device, including this one.</p>
      </div>
    </Panel>
  )
}
