/**
 * THE AUCTION DIRECTORY — every house worth knowing, who may buy there, and
 * whether Gavel can read or bid on it by API.
 *
 * Honesty first: most car auctions have NO public API. The two "salvage
 * giants" (Copart, IAA) sell to the public in many states but through their
 * own sites; the dealer lanes (Manheim, ADESA) need a dealer licence; the
 * enthusiast sites (Cars & Bids, Bring a Trailer) have no developer programme.
 * eBay Motors is the one with an official, free API, and that is the source
 * Gavel reads live. The rest are here so a member always knows where to go,
 * what it costs to register, and what to expect on the day.
 *
 * Fees change. Each entry carries the fee as published when this was written,
 * and a link to check it. Where a house uses a sliding scale, no number is
 * invented: the entry says "sliding scale" and points at the calculator.
 */

export type AuctionHouse = {
  id: string
  name: string
  url: string
  /** 'public' anyone may buy; 'public-some-states' public in many states, dealer-only in others; 'dealer' licence required; 'broker' public via a registered broker. */
  access: 'public' | 'public-some-states' | 'dealer' | 'broker'
  /** What the house is for. */
  best: string
  /** What the inventory looks like — and the starter-mode caution. */
  inventory: string
  /** Registration cost and what it takes. */
  register: string
  /** Buyer fee as published. */
  buyerFee: string
  feeUrl: string
  /** Does Gavel read it live? */
  api: 'official' | 'none'
  /** Bidding from Gavel is possible only when the house has a bidding API. None do today. */
  bidApi: boolean
  /** In person? */
  inPerson: boolean
  /** Open a search on the house for this make/model. */
  searchUrl: (q: string) => string
  starterNote: string
}

export const AUCTION_HOUSES: AuctionHouse[] = [
  {
    id: 'ebay',
    name: 'eBay Motors',
    url: 'https://www.ebay.com/motors',
    access: 'public',
    best: 'The biggest public marketplace with a real developer API. Auctions and Buy It Now, private sellers and dealers, every make.',
    inventory: 'Everything from beaters to supercars. Titles are described by the seller, so read the listing and pull the VIN. Vehicle Purchase Protection covers some fraud cases.',
    register: 'Free eBay account. No licence. Payment and pickup are arranged with the seller after the auction ends.',
    buyerFee: 'No buyer fee on vehicles (the seller pays the listing fee).',
    feeUrl: 'https://www.ebay.com/help/selling/fees-credits-invoices/motors-fees',
    api: 'official',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.ebay.com/sch/Cars-Trucks/6001/i.html?_nkw=${encodeURIComponent(q)}&_sop=1`,
    starterNote: 'Best first stop. You can bid from home, there is no buyer fee, and the seller must hand you a title. Always meet the seller with the car and the title before paying the balance.',
  },
  {
    id: 'carsandbids',
    name: 'Cars & Bids',
    url: 'https://carsandbids.com',
    access: 'public',
    best: 'Enthusiast cars from 1981 to today, every listing curated and photographed with a written inspection of known flaws.',
    inventory: 'Modern enthusiast cars, clean titles almost always, disclosed issues. Prices are often near retail, so real steals are rarer; watch for reserve-not-met relists and weekday endings.',
    register: 'Free account plus a card on file. No licence.',
    buyerFee: '5% of the hammer price, minimum $250, maximum $7,500 (as published; check the link).',
    feeUrl: 'https://carsandbids.com/faq',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://carsandbids.com/search?q=${encodeURIComponent(q)}`,
    starterNote: 'Great for learning what cars really sell for: every past auction shows the final price and the comments where mechanics tear the car apart.',
  },
  {
    id: 'bat',
    name: 'Bring a Trailer',
    url: 'https://bringatrailer.com',
    access: 'public',
    best: 'The largest enthusiast auction. Classic to modern, strong on Porsche, BMW, Land Cruisers, air-cooled and analogue cars.',
    inventory: 'Well-documented, usually clean-title cars. Buyers are knowledgeable so bargains are rare; the comment threads are the best free education in the hobby.',
    register: 'Free account with a card on file. No licence.',
    buyerFee: '5% of the hammer price, minimum $250, maximum $7,500 (as published; check the link).',
    feeUrl: 'https://bringatrailer.com/faq/',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://bringatrailer.com/search/?s=${encodeURIComponent(q)}`,
    starterNote: 'Use the "Results" pages as your price guide for anything collectible. Sold prices are public and searchable.',
  },
  {
    id: 'copart',
    name: 'Copart',
    url: 'https://www.copart.com',
    access: 'public-some-states',
    best: 'The biggest salvage and insurance auction. Also sells clean-title fleet, repo, dealer and donated cars.',
    inventory: 'Mostly damaged or salvage-title vehicles. Filter to "Clean Title" and "Run and Drive" to find the fleet and repo cars. Photos are the only inspection unless you visit the yard. Starter mode hides the salvage lanes.',
    register: 'Basic membership is free (view only); Premier membership (about $99/year as published) is needed to bid up to the deposit limit. Some states require a dealer or business licence for certain titles; Copart lists them per state. Where you cannot register directly, a registered broker bids for you for a fee.',
    buyerFee: 'Sliding scale by sale price, plus a gate fee, an internet-bid fee and, if used, a broker fee. No single number: use the fee calculator.',
    feeUrl: 'https://www.copart.com/content/us/en/member-fees',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.copart.com/lotSearchResults?free=true&query=${encodeURIComponent(q)}`,
    starterNote: 'Set filters to Clean Title + Run and Drive + Minor Dents/Scratches. Add up every fee before you bid; on a cheap car the fees can be a third of the price.',
  },
  {
    id: 'iaa',
    name: 'IAA (Insurance Auto Auctions)',
    url: 'https://www.iaai.com',
    access: 'public-some-states',
    best: 'The other insurance giant. Clean-title lanes exist alongside the salvage.',
    inventory: 'Same picture as Copart: mostly damaged, with clean-title fleet and dealer trade-ins mixed in. Vehicle detail pages show an engine-start video on many lots.',
    register: 'Public buyer registration where the state allows it, otherwise a licensed buyer or a broker. Registration tiers carry an annual fee; check the current one.',
    buyerFee: 'Sliding scale by sale price, plus an internet-bid fee and service fees. Use the fee calculator.',
    feeUrl: 'https://www.iaai.com/buyerfees',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.iaai.com/Search?Keyword=${encodeURIComponent(q)}`,
    starterNote: 'Watch the "pre-bid" close time; many lots close in a live virtual auction at a set hour, not on a countdown.',
  },
  {
    id: 'manheim',
    name: 'Manheim',
    url: 'https://www.manheim.com',
    access: 'dealer',
    best: 'The wholesale market where dealers buy trade-ins. This is where used-car lots get their inventory.',
    inventory: 'Clean-title trade-ins, lease returns, fleet and rental returns with condition reports and grades. The best source of nice cars at wholesale, and closed to the public.',
    register: 'A state dealer licence is required. No licence, no account. Until then a licensed dealer can buy for you for a flat fee (a "dealer buying service").',
    buyerFee: 'Buy fee on a sliding scale, set per auction location. Check the location page.',
    feeUrl: 'https://www.manheim.com/publications/fees',
    api: 'none',
    bidApi: false,
    inPerson: true,
    starterNote: 'The reason to get a dealer licence. Condition reports grade every car 0–5 so you can buy without seeing it.',
    searchUrl: (q) => `https://www.manheim.com/members/powersearch?keyword=${encodeURIComponent(q)}`,
  },
  {
    id: 'adesa',
    name: 'ADESA (OPENLANE)',
    url: 'https://www.openlane.com',
    access: 'dealer',
    best: 'The second big dealer lane, strong on off-lease cars straight from the finance companies.',
    inventory: 'Clean-title off-lease and fleet cars with condition reports. Dealer only.',
    register: 'Dealer licence required.',
    buyerFee: 'Sliding scale by sale price; see the current fee schedule.',
    feeUrl: 'https://www.openlane.com/us/fees',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.openlane.com/search?q=${encodeURIComponent(q)}`,
    starterNote: 'Same rule as Manheim: dealer licence first.',
  },
  {
    id: 'acv',
    name: 'ACV Auctions',
    url: 'https://www.acvauctions.com',
    access: 'dealer',
    best: 'Online-only dealer auction with very detailed condition reports (undercarriage photos, engine sound recordings).',
    inventory: 'Dealer trade-ins, 20-minute auctions all day. Dealer only.',
    register: 'Dealer licence required.',
    buyerFee: 'Flat buy fee by price band; see the app.',
    feeUrl: 'https://www.acvauctions.com/faq',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: () => 'https://www.acvauctions.com',
    starterNote: 'Once licensed, the condition reports here are the easiest for a beginner to read.',
  },
  {
    id: 'govdeals',
    name: 'GovDeals',
    url: 'https://www.govdeals.com',
    access: 'public',
    best: 'Government surplus: police cars, city trucks, fleet sedans, seized vehicles. Anyone can bid.',
    inventory: 'Fleet-maintained, usually clean title, often high miles. Little to no photos of wear; inspection days are listed.',
    register: 'Free account. For federal cars see GSA Auctions, which Gavel reads live.',
    buyerFee: 'Buyer premium varies by seller, typically stated on each lot.',
    feeUrl: 'https://www.govdeals.com/en/help',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.govdeals.com/en/search?keyword=${encodeURIComponent(q)}`,
    starterNote: 'Cheap, honest cars with maintenance records. Ex-fleet Ford Explorers, Chevy Tahoes and Toyota Camrys are common. Good first rental-fleet candidates.',
  },
  {
    id: 'gsa',
    name: 'GSA Auctions',
    url: 'https://www.gsaauctions.gov',
    access: 'public',
    best: 'Federal government surplus: fleet sedans, pickups, SUVs and vans retired by federal agencies. Anyone can bid.',
    inventory: 'Fleet cars with maintenance records, often high miles, sold as-is. Most sell with an SF-97 (Certificate to Obtain Title), which your DMV turns into a normal title.',
    register: 'Free account at gsaauctions.gov with identity verification. No licence.',
    buyerFee: 'No buyer premium: you pay your winning bid plus any sales tax.',
    feeUrl: 'https://www.gsaauctions.gov/',
    api: 'official',
    bidApi: false,
    inPerson: true,
    searchUrl: () => 'https://www.gsaauctions.gov/auctions/auctions-list',
    starterNote: 'Gavel reads GSA live through the government\'s own Auctions API. Good first rental cars: boring, maintained, cheap. Inspection days are listed on each lot; go if you can.',
  },
  {
    id: 'marketcheck',
    name: 'MarketCheck (dealers and auctions)',
    url: 'https://www.marketcheck.com',
    access: 'public',
    best: 'A data service, not an auction: it indexes used-car listings from dealers nationwide, plus auction inventory, through one official paid API.',
    inventory: 'Retail dealer cars and auction lots. Gavel uses dealer asking prices as comparables, which makes every estimate sharper, and shows auction lots in the feed.',
    register: 'A MarketCheck API account (paid, with trial data on request). You buy each car from the dealer or auction the listing links to, under that seller\'s rules.',
    buyerFee: 'None from MarketCheck. Dealers add documentation fees, and auctions their own buyer fees; read the listing.',
    feeUrl: 'https://www.marketcheck.com/apis/pricing/',
    api: 'official',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.marketcheck.com/search?q=${encodeURIComponent(q)}`,
    starterNote: 'The single biggest upgrade to Gavel\'s pricing: with it, "what similar cars sell for" comes from hundreds of dealer listings instead of a handful.',
  },
  {
    id: 'local',
    name: 'Local public auto auctions',
    url: 'https://www.google.com/maps/search/public+auto+auction',
    access: 'public',
    best: 'Weekly in-person auctions that sell trade-ins, repos and donated cars to the public.',
    inventory: 'A mix. You can walk the lot, start the cars, look underneath. This is where to learn the rhythm of a live auction before spending real money.',
    register: 'Bring a photo ID and a deposit (cash or card, often $200–$500, refunded if you buy nothing). No licence at a public auction.',
    buyerFee: 'Stated at the door, typically a percentage of hammer with a minimum. Ask before you register.',
    feeUrl: 'https://www.google.com/maps/search/public+auto+auction',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.google.com/maps/search/public+auto+auction+${encodeURIComponent(q)}`,
    starterNote: 'Go twice without bidding. Sit near the front, watch what sells and for how much, and write it down.',
  },
  {
    id: 'collector',
    name: 'Mecum and Barrett-Jackson',
    url: 'https://www.mecum.com',
    access: 'public',
    best: 'The big televised collector auctions. Supercars, muscle, exotics, in person and online.',
    inventory: 'Collector-grade cars, usually clean title, often sold at no reserve. Prices run hot under the lights; the bargains are the unglamorous lots on the first day.',
    register: 'Bidder registration with a fee (roughly $100–$500 depending on the event) and proof of funds or a bank letter for the high tiers.',
    buyerFee: 'About 10% of hammer in person and a little more online (as published per event; check before you register).',
    feeUrl: 'https://www.mecum.com/faq/',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.mecum.com/lots/?q=${encodeURIComponent(q)}`,
    starterNote: 'Go as a spectator first; the ticket is cheap and you will see a thousand cars in a weekend.',
  },
  {
    id: 'pcarmarket',
    name: 'PCARMARKET',
    url: 'https://www.pcarmarket.com',
    access: 'public',
    best: 'Porsche specialists: 911s, Caymans, Boxsters and the odd supercar, with a Porsche-savvy crowd.',
    inventory: 'Mostly clean-title Porsches with long photo sets. A good place to learn what each 911 generation really sells for.',
    register: 'Free account and a card on file. No licence.',
    buyerFee: 'A percent of the hammer price with a minimum and a cap; the exact numbers are in the buyer agreement (check the link).',
    feeUrl: 'https://www.pcarmarket.com/buyer-agreement/',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:pcarmarket.com ' + q)}`,
    starterNote: 'If a 911 is the dream, watch twenty PCARMARKET results before you bid on one.',
  },
  {
    id: 'collectingcars',
    name: 'Collecting Cars',
    url: 'https://collectingcars.com',
    access: 'public',
    best: 'Global supercar and modern-classic auctions, run around the clock from the UK, US and elsewhere.',
    inventory: 'Supercars, modern classics and performance cars, many outside the US. Check where the car is: import, shipping and duty can add thousands.',
    register: 'Free account and a card on file. No licence.',
    buyerFee: '6% of the hammer price, minimum US$1,000, maximum US$10,000 (as published; check the link).',
    feeUrl: 'https://collectingcars.com/faqs',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:collectingcars.com ' + q)}`,
    starterNote: 'Filter to cars already in the US. A cheap car abroad is rarely cheap once it lands.',
  },
  {
    id: 'hagerty',
    name: 'Hagerty Marketplace',
    url: 'https://www.hagerty.com/marketplace',
    access: 'public',
    best: 'Classics and collector cars, run by the collector-car insurer.',
    inventory: 'Classics and modern collectibles, usually clean title with detailed listings.',
    register: 'Free account and a card on file. No licence.',
    buyerFee: '7% of the hammer price, minimum $500; no cap was found (as published; check the link).',
    feeUrl: 'https://www.hagerty.com/marketplace/faq/bid',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:hagerty.com/marketplace ' + q)}`,
    starterNote: 'The fee has no cap that we found, so on a dear car it is more than at Cars & Bids or Bring a Trailer.',
  },
  {
    id: 'dupont',
    name: 'duPont REGISTRY Live',
    url: 'https://live.dupontregistry.com',
    access: 'public',
    best: 'Exotics and supercars: Ferrari, Lamborghini, McLaren, Porsche and friends.',
    inventory: 'High-end exotics, usually clean title. Few steals; useful for learning supercar prices.',
    register: 'Register as a bidder; see the bidder guidelines.',
    buyerFee: '5% of the hammer price (as published; check the link).',
    feeUrl: 'https://live.dupontregistry.com/bidder-guidelines',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:live.dupontregistry.com ' + q)}`,
    starterNote: 'A supercar costs supercar money to keep: get a specialist inspection and a service quote before you bid.',
  },
  {
    id: 'mbmarket',
    name: 'The MB Market',
    url: 'https://thembmarket.com',
    access: 'public',
    best: 'Mercedes-Benz only, from classics to AMG.',
    inventory: 'Mercedes of every era, usually with detailed photos and history.',
    register: 'Free account and a card on file. No licence.',
    buyerFee: '4.5% of the hammer price, minimum $225, maximum $4,500 (as published; check the link).',
    feeUrl: 'https://thembmarket.com/how-it-works',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:thembmarket.com ' + q)}`,
    starterNote: 'A Mercedes specialist audience: learn the known faults of the model before you bid.',
  },
  {
    id: 'hemmings',
    name: 'Hemmings Auctions',
    url: 'https://www.hemmings.com/auction',
    access: 'public',
    best: 'American classics and muscle cars from the long-running classic-car magazine.',
    inventory: 'Classics, muscle and vintage trucks. Clean titles are common but check each one.',
    register: 'Free account. No licence.',
    buyerFee: 'A percent of the hammer price with a minimum and a cap; check the current figures on the site.',
    feeUrl: 'https://www.hemmings.com/auction',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:hemmings.com ' + q)}`,
    starterNote: 'Old cars need old-car skills: rust, wiring and parts are the hidden costs.',
  },
  {
    id: 'rmsothebys',
    name: 'RM Sotheby\'s',
    url: 'https://rmsothebys.com',
    access: 'public',
    best: 'Blue-chip collector cars at live auctions such as Monterey, Amelia Island and Arizona.',
    inventory: 'Top-end collector cars. Not a place for beginners to buy, but its results show what the best examples are worth.',
    register: 'Bidder registration with identity and financial references before each sale.',
    buyerFee: '12% of the hammer price up to $250,000 and 10% above (as published for the sale; check the link).',
    feeUrl: 'https://rmsothebys.com/auctions/mo26/bidder-info/',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:rmsothebys.com ' + q)}`,
    starterNote: 'Watch, do not buy: 10-12% on top and a fast live room work against a flip.',
  },
  {
    id: 'gooding',
    name: 'Gooding Christie\'s',
    url: 'https://www.goodingco.com',
    access: 'public',
    best: 'Blue-chip collector cars at live auctions, plus online-only sales.',
    inventory: 'Top-end collector cars. Its results are a reference for what the best examples fetch.',
    register: 'Bidder registration with identity and financial references.',
    buyerFee: 'Live sales: 12% of the hammer price, 10% above $250,000; online-only sales: 10% (as published; check the link).',
    feeUrl: 'https://www.goodingco.com/terms/',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:goodingco.com ' + q)}`,
    starterNote: 'Watch, do not buy, until you know exactly what a car is worth.',
  },
  {
    id: 'bonhams',
    name: 'Bonhams Cars',
    url: 'https://cars.bonhams.com',
    access: 'public',
    best: 'Collector cars at live and online auctions in the US and abroad.',
    inventory: 'Collector and vintage cars, from affordable classics to blue-chip.',
    register: 'Bidder registration with identity and financial references.',
    buyerFee: 'Changed on 1 October 2026; check the buyer\'s premium page before you bid.',
    feeUrl: 'https://www.bonhams.com/how-to-buy/buyers-premium-united-states/',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:bonhams.com ' + q)}`,
    starterNote: 'Check the new buyer premium first; it changed on 1 October 2026.',
  },
  {
    id: 'publicsurplus',
    name: 'Public Surplus',
    url: 'https://www.publicsurplus.com',
    access: 'public',
    best: 'Government and school-district surplus, including fleet cars, trucks and vans.',
    inventory: 'Fleet vehicles with high miles and service records. Condition varies; read every line.',
    register: 'Free account. No licence for most lots.',
    buyerFee: 'Set by each selling agency, often around 6.5% to 10% (check the lot).',
    feeUrl: 'https://www.publicsurplus.com/sms/help/public/useragree.html',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:publicsurplus.com ' + q)}`,
    starterNote: 'Fleet cars are often maintained on schedule: ask for the service records.',
  },
  {
    id: 'municibid',
    name: 'Municibid',
    url: 'https://municibid.com',
    access: 'public',
    best: 'City, county and police surplus, including fleet and police vehicles.',
    inventory: 'Fleet cars, ex-police cars and trucks. High miles are normal.',
    register: 'Account with a credit card; 18 or over. Some items need a dealer licence.',
    buyerFee: '9% of the hammer price up to $99,999.99, then tiered (as published; check the link).',
    feeUrl: 'https://support.municibid.com/en/articles/404877',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:municibid.com ' + q)}`,
    starterNote: 'Ex-police cars idle for thousands of hours: the odometer understates the wear.',
  },
  {
    id: 'propertyroom',
    name: 'PropertyRoom.com',
    url: 'https://www.propertyroom.com',
    access: 'public',
    best: 'Police impound and seized vehicles sold for police departments.',
    inventory: 'Impounded and seized cars. Condition is often unknown; many do not come with keys.',
    register: 'Free to bid.',
    buyerFee: '10%, 12% or 15% on vehicles depending on the sale (check the lot).',
    feeUrl: 'https://www.propertyroom.com',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:propertyroom.com ' + q)}`,
    starterNote: 'Assume nothing works until you have seen it start.',
  },
  {
    id: 'govplanet',
    name: 'GovPlanet',
    url: 'https://www.govplanet.com',
    access: 'public',
    best: 'Ex-military and government vehicles and equipment.',
    inventory: 'Mostly military vehicles and equipment, some sold without road titles. Not a starter source for a road car.',
    register: 'Account, 21 or over, with bidding privileges approved.',
    buyerFee: 'A sliding fee by price (check the buyer-fees page).',
    feeUrl: 'https://www.govplanet.com/buyer-fees',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:govplanet.com ' + q)}`,
    starterNote: 'Many lots cannot be registered for the road. Read the title line twice.',
  },
  {
    id: 'hibid',
    name: 'HiBid',
    url: 'https://hibid.com',
    access: 'public',
    best: 'Where many local auctioneers run their sales online, including car auctions and police lots near you.',
    inventory: 'Whatever the local auctioneer is selling: estate cars, repos, fleet and police cars.',
    register: 'Free account; each auctioneer may approve you separately.',
    buyerFee: 'Set by each auctioneer, often 10% to 18% (check the sale terms).',
    feeUrl: 'https://hibid.com',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:hibid.com ' + q)}`,
    starterNote: 'Search your city: a small local sale can have far fewer bidders than the big sites.',
  },
  {
    id: 'purplewave',
    name: 'Purple Wave',
    url: 'https://www.purplewave.com',
    access: 'public',
    best: 'No-reserve online auctions of trucks, fleet vehicles and equipment, mostly in the Midwest.',
    inventory: 'Work trucks, fleet cars and equipment, sold without reserve.',
    register: 'Free account.',
    buyerFee: '10% buyer premium on most sales; some 15%; minimum $100 (as published; check the link).',
    feeUrl: 'https://www.purplewave.com/auction/legal/terms',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:purplewave.com ' + q)}`,
    starterNote: 'No reserve means it sells: good for bargains if you have checked the truck.',
  },
  {
    id: 'treasury',
    name: 'US Treasury seized vehicles (CWS)',
    url: 'https://www.cwsmarketing.com',
    access: 'public',
    best: 'Vehicles seized by federal agencies, sold for the Treasury.',
    inventory: 'Seized cars of every kind, from ordinary to luxury. Condition varies.',
    register: 'Free account with a photo ID upload.',
    buyerFee: 'No buyer premium on Treasury and Customs sales (as published; check the link).',
    feeUrl: 'https://www.cwsmarketing.com/faqs',
    api: 'none',
    bidApi: false,
    inPerson: false,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:cwsmarketing.com ' + q)}`,
    starterNote: 'No buyer premium: the bid is the price, before tax and transport.',
  },
  {
    id: 'americasaa',
    name: 'America\'s Auto Auction',
    url: 'https://www.americasaa.com',
    access: 'dealer',
    best: 'A chain of wholesale auctions for dealers, with some public and GSA sales.',
    inventory: 'Dealer trade-ins and fleet cars. Most lanes are dealers only.',
    register: 'Dealers through AuctionACCESS; check each location for public sales.',
    buyerFee: 'Sliding scale set by each location (check before the sale).',
    feeUrl: 'https://www.americasaa.com',
    api: 'none',
    bidApi: false,
    inPerson: true,
    searchUrl: (q) => `https://www.google.com/search?q=${encodeURIComponent('site:americasaa.com ' + q)}`,
    starterNote: 'Ask your local location whether it runs public or GSA sales.',
  }
]

export function houseById(id: string): AuctionHouse | undefined {
  return AUCTION_HOUSES.find((h) => h.id === id)
}

/**
 * How the Auctions screen groups the houses, in the order a beginner should
 * meet them, with what each group is best for. Every house is in exactly one
 * group (a test checks).
 */
export const HOUSE_GROUPS: Array<{ id: string; title: string; bestFor: string; houses: string[] }> = [
  { id: 'live', title: 'Read live by Gavel', bestFor: 'Cars that come into your Feed and the Sniper by themselves once the source is connected.', houses: ['ebay', 'gsa', 'marketcheck'] },
  { id: 'enthusiast', title: 'Enthusiast and supercar, online', bestFor: 'Supercars, Porsches and cars that hold their value. Clean titles, public results to learn prices from, fees around 5% with caps.', houses: ['carsandbids', 'bat', 'pcarmarket', 'collectingcars', 'dupont', 'hagerty', 'mbmarket', 'hemmings'] },
  { id: 'government', title: 'Government, police and seized', bestFor: 'A first rental car: fleet cars with service records, often clean titles, low or no buyer premium.', houses: ['govdeals', 'publicsurplus', 'municibid', 'treasury', 'propertyroom', 'purplewave', 'govplanet'] },
  { id: 'salvage', title: 'Salvage and insurance, public in many states', bestFor: 'The biggest volume and the deepest discounts, but mostly damaged cars: filter to clean titles and "run and drive", and expect sliding-scale fees.', houses: ['copart', 'iaa'] },
  { id: 'local', title: 'Local auctions near you', bestFor: 'Fewer bidders than the big sites. Go in person first to learn.', houses: ['hibid', 'local'] },
  { id: 'collector', title: 'Live collector auctions: watch first', bestFor: 'Learning what the best examples fetch. 10-12% on top makes a flip hard for a beginner.', houses: ['collector', 'rmsothebys', 'gooding', 'bonhams'] },
  { id: 'dealer', title: 'Dealer-only wholesale', bestFor: 'Where used-car lots buy. Needs a dealer licence, so later, not first.', houses: ['manheim', 'adesa', 'acv', 'americasaa'] },
]
